<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "https://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>configURL</key>
	<string>https://mobile.video.qq.com/fcgi-bin/dout_iphone?auto_id=28</string>
	<key>p2pConfigURL</key>
	<string>https://mcgi.v.qq.com/getmfomat?cmd=get_ios_config&amp;platform=iphone</string>
	<key>errorCodeConfigURL</key>
	<string>https://mcgi.v.qq.com/commdatav2?cmd=29</string>
	<key>homeTitleBarURL</key>
	<string>https://mobile.video.qq.com/fcgi-bin/dout_iphone?auto_id=62</string>
	<key>specialPageURL</key>
	<string>https://mobile.video.qq.com/fcgi-bin/getcmsdata</string>
	<key>specialModuleURL</key>
	<string>https://mobile.video.qq.com/fcgi-bin/getcmsdata</string>
	<key>essentialPageURL</key>
	<string>https://mobile.video.qq.com/fcgi-bin/getjimudata</string>
	<key>essentialModuleURL</key>
	<string>https://mobile.video.qq.com/fcgi-bin/getjimudata</string>
	<key>essentialHotspotPageURL</key>
	<string>https://mobile.video.qq.com/fcgi-bin/getjimudata</string>
	<key>essentialHotspotModuleURL</key>
	<string>https://mobile.video.qq.com/fcgi-bin/getjimudata</string>
	<key>channelListURL</key>
	<string>https://mobile.video.qq.com/fcgi-bin/dout_iphone?auto_id=1</string>
	<key>videoListURL</key>
	<string>https://mobile.video.qq.com/fcgi-bin/dout_iphone</string>
	<key>selectedVideoListURL</key>
	<string>https://mobile.video.qq.com/fcgi-bin/dout_iphone?auto_id=59</string>
	<key>indexDataURL</key>
	<string>https://mobile.video.qq.com/fcgi-bin/dout_iphone</string>
	<key>coverDetailURL</key>
	<string>https://live.qq.com/json/ipad/cover</string>
	<key>shortDetailURL</key>
	<string>https://ncgi.video.qq.com/tvideo/fcgi-bin/vp_iphone</string>
	<key>shortRelatedURL</key>
	<string>https://ncgi.video.qq.com/tvideo/fcgi-bin/videorelcmt</string>
	<key>varietyRelatedURL2</key>
	<string>https://live.qq.com/json/ipad/review</string>
	<key>columeDetailCGI</key>
	<string>https://live.qq.com/json/ipad/column</string>
	<key>varietyRelatedURL1</key>
	<string>https://live.qq.com/json/ipad/column</string>
	<key>varietyExtrasURL</key>
	<string>https://live.qq.com/json/ipad/column</string>
	<key>coverRelatedURL</key>
	<string>https://mobile.video.qq.com/fcgi-bin/dout_iphone?auto_id=407</string>
	<key>laterCoverRelatedURL</key>
	<string>https://like.video.qq.com/fcgi-bin/rmd_mobile</string>
	<key>personalRecmdURL</key>
	<string>https://like.video.qq.com/fcgi-bin/like</string>
	<key>personalRecmdNoFeelingURL</key>
	<string>https://like.video.qq.com/fcgi-bin/nofeeling</string>
	<key>playCountURL</key>
	<string>https://sns.video.qq.com/tvideo/fcgi-bin/batchgetplaymount</string>
	<key>videoSizeListURL</key>
	<string>https://vv.video.qq.com/getvfsize</string>
	<key>searchHotKeywords</key>
	<string>https://mobile.video.qq.com/fcgi-bin/dout_iphone?auto_id=938</string>
	<key>searchKeywordsURL</key>
	<string>https://s.video.qq.com/smt_iphone</string>
	<key>searchChanelHotURL</key>
	<string>https://sns.video.qq.com/fcgi-bin/dlib/dataout?auto_id=1114</string>
	<key>searchResultsURL</key>
	<string>https://s.video.qq.com/srh_iphone</string>
	<key>liveListURL</key>
	<string>https://mobile.video.qq.com/fcgi-bin/dout_iphone?auto_id=24</string>
	<key>liveProgramsURL</key>
	<string>https://ipad.zb.qq.com/program_xml</string>
	<key>liveProgramInfoURL</key>
	<string>https://zb.s.qq.com/getproginfo.fcgi</string>
	<key>liveProgramQueryURL</key>
	<string>https://zb.v.qq.com:1863</string>
	<key>liveProgramVInfoURL</key>
	<string>https://info.zb.video.qq.com</string>
	<key>liveProgramVInfoBKURL</key>
	<string>https://bk.info.zb.video.qq.com</string>
	<key>utopiaLiveProgramVInfoURL</key>
	<string>https://utopia.zb.qq.com</string>
	<key>utopiaLiveProgramVInfoBKURL</key>
	<string>https://bk.utopia.zb.qq.com</string>
	<key>weiboCheckWithQQ</key>
	<string>https://sns.video.qq.com/fcgi-bin/liveportal/pc_micro_blog</string>
	<key>weiboSendWithQQPlayer</key>
	<string>https://sns.video.qq.com/fcgi-bin/liveportal/pc_micro_blog</string>
	<key>weiboSendWithQQDetail</key>
	<string>https://sns.video.qq.com/fcgi-bin/liveportal/business_micro_blog</string>
	<key>weiboRedirectURL</key>
	<string>https://sns.video.qq.com/fcgi-bin/liveportal/get_real_url</string>
	<key>shareOfMBlogURL</key>
	<string>https://vg.video.qq.com/vgshare</string>
	<key>specialTopicShareURL</key>
	<string>https://m.v.qq.com/topic/topic.html</string>
	<key>getCommentsURL</key>
	<string>https://sns.video.qq.com/fcgi-bin/liveportal/comment</string>
	<key>postCommentURL</key>
	<string>https://sns.video.qq.com/fcgi-bin/liveportal/postcomment</string>
	<key>getTxNewsCommentsURLByVideoType</key>
	<string>https://comment5.news.qq.com/php2009/greplyBycid2.php</string>
	<key>postTxNewsCommentURL</key>
	<string>https://input2.comment.qq.com/pubreplyapp.php</string>
	<key>infoReportUrl</key>
	<string>https://mobile.video.qq.com/fcgi-bin/info_report</string>
	<key>qzoneCheckWithQQ</key>
	<string>https://mcgi.v.qq.com/share?dest=qzone&amp;cmd=check</string>
	<key>qzoneSendWithQQ</key>
	<string>https://mcgi.v.qq.com/share?dest=qzone&amp;cmd=share</string>
	<key>sinaAuthorizeWithQQ</key>
	<string>https://mcgi.v.qq.com/share?dest=sina&amp;cmd=check</string>
	<key>shortURL</key>
	<string>https://mcgi.v.qq.com/shorten?dest=qweibo&amp;cmd=shorten</string>
	<key>geturlURL</key>
	<string>https://vv.video.qq.com/geturl</string>
	<key>gethlsURL</key>
	<string>https://vv.video.qq.com/gethls</string>
	<key>getkeyURL</key>
	<string>https://vv.video.qq.com/getkey</string>
	<key>getvKeyURL</key>
	<string>https://vv.video.qq.com/getvkey</string>
	<key>getvbKeyURL</key>
	<string>https://vv.video.qq.com/getvbkey</string>
	<key>getinfoURL</key>
	<string>https://vv.video.qq.com/getinfo</string>
	<key>getUserIpURL</key>
	<string>https://aid.video.qq.com/fcgi-bin/userip</string>
	<key>getspeedURL</key>
	<string>https://vv.video.qq.com/getspeed</string>
	<key>weiboSendURL</key>
	<string>https://sns.video.qq.com/fcgi-bin/liveportal/business_micro_blog</string>
	<key>sinaSendWithQQ</key>
	<string>https://mcgi.v.qq.com/share?dest=sina&amp;cmd=share</string>
	<key>getbKeyURL</key>
	<string>https://vv.video.qq.com/getbkey</string>
	<key>getvinfoURL</key>
	<string>https://vv.video.qq.com/getvinfo</string>
	<key>checkTimeURL</key>
	<string>https://vv.video.qq.com/checktime</string>
	<key>getsizeURL</key>
	<string>https://vv.video.qq.com/getinfo</string>
	<key>videoStoreURL</key>
	<string>https://video.store.qq.com</string>
	<key>OZStatURL</key>
	<string>https://rcgi.video.qq.com/stts_qqlivehd_start</string>
	<key>userCenterHeaderBgURL</key>
	<string>https://mobile.video.qq.com/fcgi-bin/dout_iphone?auto_id=55</string>
	<key>playbackReportURL</key>
	<string>https://rcgi.video.qq.com/report/play</string>
	<key>crashReportURL</key>
	<string>https://rcgi.video.qq.com/crash_report?cmd=1017</string>
	<key>uploadTokenURL</key>
	<string>https://sns.video.qq.com/fcgi-bin/dlib/uptoken</string>
	<key>appRecommURL</key>
	<string>https://mobile.video.qq.com/fcgi-bin/dout_iphone?auto_id=33</string>
	<key>feedbackURL</key>
	<string>https://zb.s.qq.com/reportinfo.fcgi?proxy=1</string>
	<key>ipAppealingURL</key>
	<string>https://zb.s.qq.com/reportinfo.fcgi?iplimit=1</string>
	<key>sharePlayURLWithType</key>
	<string>https://m.v.qq.com/play/play.html</string>
	<key>webPlayURLWithTypeCV</key>
	<string>https://m.v.qq.com/play.html?cid={cid}&amp;type={type}&amp;vid={vid}</string>
	<key>webPlayURLWithTypeC</key>
	<string>https://m.v.qq.com/play.html?cid={cid}&amp;type={type}</string>
	<key>webPlayURLWithTypeV</key>
	<string>https://m.v.qq.com/play.html?type={type}&amp;vid={vid}&amp;title={title}</string>
	<key>webPlayURLWithChannelID</key>
	<string>https://m.v.qq.com/play.html?type={type}&amp;cnlid={cnlid}</string>
	<key>payBillURL</key>
	<string>https://pay.video.qq.com/fcgi-bin/pay</string>
	<key>payBillListURL</key>
	<string>https://pay.video.qq.com/fcgi-bin/order</string>
	<key>vipStatusURL</key>
	<string>https://pay.video.qq.com/fcgi-bin/payvip</string>
	<key>userTipURL</key>
	<string>https://3g.v.qq.com/iphone/help.html</string>
	<key>getAttentionURL</key>
	<string>https://mcgi.v.qq.com/tvattent?getorder=1</string>
	<key>baseAttentionURL</key>
	<string>https://mcgi.v.qq.com/tvattent</string>
	<key>UpPushStateURL</key>
	<string>https://mcgi.v.qq.com/push_control?cmd=1</string>
	<key>persionInterestURL</key>
	<string>https://like.video.qq.com/fcgi-bin/taste</string>
	<key>completeAttentionidURL</key>
	<string>https://mcgi.v.qq.com/get_cid?cmd=1</string>
	<key>addAttentionURL</key>
	<string>https://mcgi.v.qq.com/tvattent?cmd=2</string>
	<key>deleteAttentionURL</key>
	<string>https://mcgi.v.qq.com/tvattent?cmd=3</string>
	<key>getUserAttentionsURL</key>
	<string>https://mcgi.v.qq.com/tvattent?cmd=4</string>
	<key>syncSubAttentionURL</key>
	<string>https://mcgi.v.qq.com/tvattent?cmd=5</string>
	<key>cancelSyncSubAttentionURL</key>
	<string>https://mcgi.v.qq.com/tvattent?cmd=6</string>
	<key>deleteAllAttentionsURLLogin</key>
	<string>https://mcgi.v.qq.com/tvattent?cmd=7</string>
	<key>deleteAllAttentionsURLNone</key>
	<string>https://mcgi.v.qq.com/tvattent?cmd=8</string>
	<key>downToDeviceSubAttentionURL</key>
	<string>https://mcgi.v.qq.com/tvattent?cmd=9</string>
	<key>syncWithoutLocalSubAttentionURL</key>
	<string>https://mcgi.v.qq.com/tvattent?cmd=10</string>
	<key>queryCidURL</key>
	<string>https://data.video.qq.com/fcgi-bin/field_tmpl?tid=15</string>
	<key>adsConfigURL</key>
	<string>https://mcgi.v.qq.com/commdatav2?cmd=36</string>
	<key>homeAttentionShowURL</key>
	<string>https://mcgi.v.qq.com/commdatav2?cmd=41</string>
	<key>homeAttentionRecommendURL</key>
	<string>https://mcgi.v.qq.com/commdatav2?cmd=42</string>
	<key>MMRecommendMovie</key>
	<string>https://mcgi.v.qq.com/recent_view</string>
	<key>syncTimeStamp</key>
	<string>https://ncgi.video.qq.com/tvideo/fcgi-bin/centerstamp</string>
	<key>syncHistoryListURL</key>
	<string>https://ncgi.video.qq.com/tvideo/fcgi-bin/stampview</string>
	<key>syncHistorySingleAddURL</key>
	<string>https://rcgi.video.qq.com/report/mobmyview</string>
	<key>syncHistoryNewReport</key>
	<string>https://vg.video.qq.com/domain/recomm/report_recommend</string>
	<key>syncHistorySingleDelteURL</key>
	<string>https://ncgi.video.qq.com/tvideo/fcgi-bin/myview</string>
	<key>syncHistoryAllDelteURL</key>
	<string>https://ncgi.video.qq.com/tvideo/fcgi-bin/myview?t=5</string>
	<key>homeRecmdChannelList</key>
	<string>https://mobile.video.qq.com/fcgi-bin/dout_iphone?auto_id=65</string>
	<key>homeNewChannelTip</key>
	<string>https://mcgi.v.qq.com/commdatav2?cmd=30</string>
	<key>liveChannelCGI</key>
	<string>https://mobile.video.qq.com/fcgi-bin/dout_iphone?auto_id=70</string>
	<key>worldCupFocusViewCGI</key>
	<string>https://mobile.video.qq.com/fcgi-bin/getjimudata</string>
	<key>liveFocusViewCGI</key>
	<string>https://mobile.video.qq.com/fcgi-bin/getjimudata</string>
	<key>liveGameCGI</key>
	<string>https://mobile.video.qq.com/fcgi-bin/getjimudata</string>
	<key>liveGameTalkerListCGI</key>
	<string>https://mobile.video.qq.com/fcgi-bin/getjimudata</string>
	<key>liveGameContestListCGI</key>
	<string>https://mcgi.v.qq.com/getgameinfo</string>
	<key>liveGameContestCGI</key>
	<string>https://mcgi.v.qq.com/getgameinfo</string>
	<key>liveGameHotCGI</key>
	<string>https://mobile.video.qq.com/fcgi-bin/getjimudata</string>
	<key>worldCupAllTopicCGI</key>
	<string>https://mobile.video.qq.com/fcgi-bin/getjimudata</string>
	<key>liveSportCGI</key>
	<string>https://mobile.video.qq.com/fcgi-bin/getjimudata</string>
	<key>liveSportAllTopicCGI</key>
	<string>https://mobile.video.qq.com/fcgi-bin/getjimudata</string>
	<key>liveSportOtherTopicCGI</key>
	<string>https://mobile.video.qq.com/fcgi-bin/dout_iphone?auto_id=72</string>
	<key>liveGameTalkerHistoryCGI</key>
	<string>https://mobile.video.qq.com/fcgi-bin/dout_iphone?auto_id=73</string>
	<key>liveSportCompetitionCGI</key>
	<string>https://mcgi.v.qq.com/getmatchinfo</string>
	<key>liveSportMatchCGI</key>
	<string>https://mcgi.v.qq.com/getmatchinfo</string>
	<key>liveSportOnlineViewerCGI</key>
	<string>https://mcgi.v.qq.com/getchannelon</string>
	<key>liveSportAttendNumCGI</key>
	<string>https://mcgi.v.qq.com/commdatav2</string>
	<key>detailPageViewListURL</key>
	<string>https://mobile.video.qq.com/fcgi-bin/dout_ex?auto_id=1176</string>
	<key>liveShareURL</key>
	<string>https://m.v.qq.com/live.html</string>
	<key>liveTVStationShareURL</key>
	<string>https://m.v.qq.com/live.html</string>
	<key>openSearchURL</key>
	<string>https://m.v.qq.com/play.html</string>
	<key>liveMatchVideoListCGI</key>
	<string>https://mobile.video.qq.com/fcgi-bin/dout_iphone?auto_id=77</string>
	<key>momentPutPublishURL</key>
	<string>https://vg.video.qq.com/msgadd</string>
	<key>momentPutCommentURL</key>
	<string>https://vg.video.qq.com/msgcomment</string>
	<key>momentPutLikeURL</key>
	<string>https://vg.video.qq.com/msglike</string>
	<key>momentDeleteItemURL</key>
	<string>https://vg.video.qq.com/msgdelete</string>
	<key>momentUserLogInURL</key>
	<string>https://vg.video.qq.com/domain/user/login</string>
	<key>momentAutoLogInURL</key>
	<string>https://vgauto.video.qq.com/domain/user/freshtoken</string>
	<key>momentUserLogOutURL</key>
	<string>https://vg.video.qq.com/domain/user/logout</string>
	<key>momentUserCenterInfoURL</key>
	<string>https://vg.video.qq.com/domain/user/user_center</string>
	<key>momentGetUnreadCountURL</key>
	<string>https://vgauto.video.qq.com/getreceivecount</string>
	<key>momentGetUnreadCountAndFeedURL</key>
	<string>https://vgauto.video.qq.com/domain/timeline/detect_new</string>
	<key>momentGetFriendListURL</key>
	<string>https://vg.video.qq.com/getfriends</string>
	<key>momentGetHotPhotoURL</key>
	<string>https://vg.video.qq.com/gethotphoto</string>
	<key>momentGetCinemaRankURL</key>
	<string>https://mobile.video.qq.com/fcgi-bin/getjimudata</string>
	<key>voteGetRankingURL</key>
	<string>https://panshi.qq.com/vote</string>
	<key>voteGetGroupInfoURL</key>
	<string>https://mcgi.v.qq.com/getgroupinfo</string>
	<key>voteSendVoteUserURL</key>
	<string>https://panshi.qq.com/vote</string>
	<key>voteSendVoteUserURLForLiveV3</key>
	<string>https://panshi.qq.com</string>
	<key>voteGetVideoListURL</key>
	<string>https://mobile.video.qq.com/fcgi-bin/dout_iphone?auto_id=84</string>
	<key>hotspotHomeRecmdChannelList</key>
	<string>https://mobile.video.qq.com/fcgi-bin/dout_iphone?auto_id=65</string>
	<key>reboSubCategoryURL</key>
	<string>https://mobile.video.qq.com/fcgi-bin/dout_iphone</string>
	<key>liveListNewURL</key>
	<string>https://data.v.qq.com/live/api/category</string>
	<key>liveProgramsNewURL</key>
	<string>https://data.v.qq.com/live/api/channel</string>
	<key>excReportServerURL</key>
	<string>mdevstat.qqlive.qq.com</string>
	<key>defaultPlaybackServerUrl</key>
	<string>https://video.dispatch.tc.qq.com</string>
	<key>personalizationUrlCGI</key>
	<string>https://tencent.perserv-cn.seacert.com:8080</string>
	<key>licenseResourceUrlCGI</key>
	<string>https://mbs.video.qq.com</string>
	<key>momentUploadPhotoURL</key>
	<string>https://vgps.video.qq.com/picStoreSrv/picUpload</string>
	<key>momentInviteFriendsURL</key>
	<string>https://m.v.qq.com/d/download_wx.html</string>
	<key>momentGetPrivacySingleURL</key>
	<string>https://vg.video.qq.com/domain/privacy/get_single</string>
	<key>momentSetPrivacySingleURL</key>
	<string>https://vg.video.qq.com/domain/privacy/set_single</string>
	<key>momentGetPrivacyBlackListURL</key>
	<string>https://vg.video.qq.com/domain/privacy/get_blacklist</string>
	<key>momentSetPrivacyBlackListURL</key>
	<string>https://vg.video.qq.com/domain/privacy/set_blacklist</string>
	<key>momentGetUserCenterInfoURL</key>
	<string>https://vg.video.qq.com/domain/user/user_center</string>
	<key>momentVideoTimelineURL</key>
	<string>https://vg.video.qq.com/domain/timeline/video_timeline</string>
	<key>momentVideoLikeURL</key>
	<string>https://vg.video.qq.com/domain/timeline/video_like</string>
	<key>momentReceiveTimelineURL</key>
	<string>https://vg.video.qq.com/domain/timeline/receive_timeline</string>
	<key>momentHomeTimelineURL</key>
	<string>https://vg.video.qq.com/domain/timeline/home_timeline</string>
	<key>momentUserTimelineURL</key>
	<string>https://vg.video.qq.com/domain/timeline/user_timeline</string>
	<key>momentMsgCommentTimelineURL</key>
	<string>https://vg.video.qq.com/domain/timeline/msg_comment_timeline</string>
	<key>momentNewFeedTimelineURL</key>
	<string>https://vg.video.qq.com/domain/timeline/new_timeline</string>
	<key>momentVideoRecommendURL</key>
	<string>https://vg.video.qq.com/domain/recomm/friend_recommend</string>
	<key>momentBindQQURL</key>
	<string>https://vg.video.qq.com/domain/user/bind</string>
	<key>momentUnbindQQURL</key>
	<string>https://vg.video.qq.com/domain/user/unbind</string>
	<key>momentToUserIDURL</key>
	<string>https://vg.video.qq.com/domain/user/msgid2uin</string>
	<key>userHelpUrl</key>
	<string>https://kf.qq.com/touch/product/video_platform_app.html?ADTAG=veda.video.app</string>
	<key>iapGetVipIntroURL</key>
	<string>https://film.qq.com/app/iphonevip</string>
	<key>iapHollywoodMoviesURL</key>
	<string>https://film.qq.com/app/iphonemovie</string>
	<key>iapHollywoodPayURL</key>
	<string>https://film.qq.com/app/iphonediscount</string>
	<key>iapVisitorBindUINURL</key>
	<string>https://pay.video.qq.com/fcgi-bin/trans_guidvip_to_uin</string>
	<key>attentUpdataServer</key>
	<string>https://mattent.video.qq.com:14325/video/open/attent?cmd=2</string>
	<key>momentGetPrivacyMaskListURL</key>
	<string>https://vg.video.qq.com/getdefblacklist</string>
	<key>starPeopleDetailURL</key>
	<string>https://live.qq.com/json/ipad/people</string>
	<key>starPeopleActivityURL</key>
	<string>https://zgv.video.qq.com/getstarnews</string>
	<key>starPeopleAssociaeURL</key>
	<string>https://mcgi.v.qq.com/star_searchlist</string>
	<key>momentPutFollowURL</key>
	<string>https://vg.video.qq.com/domain/timeline/feed_follow</string>
	<key>voteRankingShareURL</key>
	<string>https://m.v.qq.com/activity/voice/poplist.html</string>
	<key>banabaBarrageFromWebClientURL</key>
	<string>https://bullet.video.qq.com/fcgi-bin</string>
	<key>banabaBarrageURL</key>
	<string>https://mfm.video.qq.com</string>
	<key>voiceAdImage</key>
	<string>https://mobile.video.qq.com/fcgi-bin/dout_iphone?auto_id=95</string>
	<key>adImagesURL</key>
	<string>https://mobile.video.qq.com/fcgi-bin/dout_iphone?auto_id=25</string>
	<key>momentReportURL</key>
	<string>https://vg.video.qq.com/domain/recomm/report_recommend?otype=json</string>
	<key>unicomVideoQQUrl</key>
	<string>https://vv.video.qq.com</string>
	<key>unicomBaseUrl</key>
	<string>https://114.255.201.238:8090/video</string>
	<key>unicomCheckUserIp</key>
	<string>https://mcgi.v.qq.com/unicom/check_user_ip</string>
	<key>unicomCheckUserOrder</key>
	<string>https://mcgi.v.qq.com/unicom/check_user_order</string>
	<key>unicomGetvinfoURL</key>
	<string>https://vv.video.qq.com/getvinfo</string>
	<key>unicomGetvKeyURL</key>
	<string>https://vv.video.qq.com/getvkey</string>
	<key>unicomGetvbKeyURL</key>
	<string>https://vv.video.qq.com/getvbkey</string>
	<key>videoTipsURL</key>
	<string>https://vg.video.qq.com/domain/tips/video_tips</string>
	<key>shareCountsURL</key>
	<string>https://vg.video.qq.com/domain/tips/share_cnt</string>
	<key>drawingResourceURL</key>
	<string>https://vgps.video.qq.com:8002/graffiti</string>
	<key>commentUrl</key>
	<string>https://cm.v.qq.com:8080</string>
	<key>movieVoucherURL</key>
	<string>https://pay.video.qq.com/fcgi-bin/getmyticket</string>
	<key>userMovieTicketsURL</key>
	<string>https://pay.video.qq.com/fcgi-bin/user_ticket</string>
	<key>visitorGiveTicketURL</key>
	<string>https://pay.video.qq.com/fcgi-bin/ykgiveticket</string>
	<key>movieTicketTradeURL</key>
	<string>https://pay.video.qq.com/fcgi-bin/ticket_trade</string>
	<key>newMobileDetailURL</key>
	<string>https://mdt.video.qq.com/mobile_detail</string>
	<key>newMobileDetailMomentRateURL</key>
	<string>https://mcgi.v.qq.com/video_sharelist</string>
	<key>newMobileDetailDoubanListURL</key>
	<string>https://mcgi.v.qq.com/douban</string>
	<key>unicomH5BaseUrl</key>
	<string>https://m.v.qq.com/activity/wo/free.html</string>
	<key>interactiveVoteHitPointURL</key>
	<string>https://sns.video.qq.com/fcgi-bin/liveportal/get_video_mark</string>
	<key>interactiveVoteH5URL</key>
	<string>https://m.v.qq.com/activity/qqvideo/H5InteractAPP.html</string>
	<key>hollywoodPrivilegeIntroduceURL</key>
	<string>https://film.qq.com/app/hlw.html</string>
	<key>hollywoodLoginPrivacyURL</key>
	<string>https://m.v.qq.com/about/privacy.html</string>
	<key>hollywoodQQRegisterURL</key>
	<string>https://zc.qq.com/chs/index.html</string>
	<key>starThemeURL</key>
	<string>https://minfo.video.qq.com/getstarinfo?cmd=3</string>
	<key>starThemeReportURL</key>
	<string>https://minfo.video.qq.com/getstarinfo?cmd=2</string>
	<key>starThemeDiyURL</key>
	<string>https://www.qq.com</string>
	<key>starThemeShareURL</key>
	<string>https://m.v.qq.com/activity/star/star.html?starthemeid=</string>
	<key>appLiveCommentUploadPhoto</key>
	<string>https://upload.coral.qq.com/image/upload</string>
	<key>appLivePostComment</key>
	<string>https://abc.qq.com/livepostcomment</string>
	<key>qlGetImagetag</key>
	<string>https://data.video.qq.com/fcgi-bin/data?tid=137</string>
	<key>mapPoiURL</key>
	<string>https://apis.map.qq.com/ws/place/v1/search</string>
	<key>appLiveTakingRoom</key>
	<string>https://live.coral.qq.com/</string>
	<key>appLiveGetTimelineComment</key>
	<string>https://video.coral.qq.com/article/comment/timeline/video</string>
	<key>appLiveGetReplyComment</key>
	<string>https://video.coral.qq.com/article/comment/reply/video</string>
	<key>appLiveGetHostManComment</key>
	<string>https://live.mobile.video.qq.com/fcgi-bin/host_comment</string>
	<key>appLiveWriteComment</key>
	<string>https://w.coral.qq.com/comment/write</string>
	<key>livePrecentListURL</key>
	<string>https://pay.video.qq.com/fcgi-bin/get_tools</string>
	<key>liveDetailURL</key>
	<string>https://live.mobile.video.qq.com/fcgi-bin/livedetail</string>
	<key>liveDetailPollURL</key>
	<string>https://live.mobile.video.qq.com/fcgi-bin/live_poll</string>
	<key>liveDetailGiveToolURL</key>
	<string>https://pay.video.qq.com/fcgi-bin/give_tools</string>
	<key>liveRankingURL</key>
	<string>https://live.mobile.video.qq.com/fcgi-bin/get_live_rank</string>
	<key>liveToolH5EffectURL</key>
	<string>https://m.v.qq.com/activity/qqvideo/effect/H5Effect.html</string>
	<key>appPropsUploadPhotoURL</key>
	<string>https://upload.coral.qq.com/image/upload</string>
	<key>appLiveGetCommentDetail</key>
	<string>https://video.coral.qq.com/origin/reply/timeline/video</string>
	<key>playInfoReportURL</key>
	<string>https://rcgi.video.qq.com/report/play</string>
	<key>playInfoBatchReportURL</key>
	<string>https://rcgi.video.qq.com/report/bplay</string>
	<key>eduGetvinfoURL</key>
	<string>https://sv.video.qq.com/edugetvinfo</string>
	<key>eduGetvKeyURL</key>
	<string>https://sv.video.qq.com/edugetvkey</string>
	<key>eduGetvbKeyURL</key>
	<string>https://sv.video.qq.com/edugetvbkey</string>
	<key>JCEServiceURL</key>
	<string>https://omaios.video.qq.com:80</string>
</dict>
</plist>
